## 1D Array with Numpy


In [0]:
import numpy as np
import torch


In [3]:
t= np.array([0.,1.,2.,3.,4.,5.,6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [4]:
print('Rank of t: ', t.ndim)
print('Shape of t:',t.shape)

Rank of t:  1
Shape of t: (7,)


In [6]:
print('t[0] t[1] t[-1] = ',t[0],t[1],t[-1]) # Element
print('t[2:5] t[4:-1] = ',t[2:5],t[4:-1]) # Slicing
print('t[:2] t[3:] = ',t[:5],t[3:]) # Slicing



t[0] t[1] t[-1] =  0.0 1.0 6.0
t[2:5] t[4:-1] =  [2. 3. 4.] [4. 5.]
t[:2] t[3:] =  [0. 1. 2. 3. 4.] [3. 4. 5. 6.]


## 2D Array with Numpy

In [7]:
t = np.array([[1.,2.,3.],[4.,5.,6.],[7.,8.,9.],[10.,11.,12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [8]:
print('Rank of t: ', t.ndim)
print('Shape of t:',t.shape)

Rank of t:  2
Shape of t: (4, 3)


In [11]:
t = torch.FloatTensor([0.,1.,2.,3.,4.,5.,6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [16]:
print(t.dim())
print(t.shape)
print(t.size())
print(t[0],t[1],t[-1])
print(t[2:5],t[4:-1]) # Slicing
print(t[:2],t[3:]) # Slicing



1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


In [18]:
t= torch.FloatTensor([[1.,2.,3.],
                      [4.,5.,6.],
                      [7.,8.,8-9.],
                      [10.,11.,12.]
                      ])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8., -1.],
        [10., 11., 12.]])


In [19]:
print(t.dim())# rank
print(t.size()) # shape
print(t[:,1]) # 첫번째 차원은 다 가져오고 두번쨰 차원에서는 1까지만 가지고 오셈
print(t[:,1].size())
print(t[:,:-1])

2
torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


## Broadcasting 


In [20]:
# Same shape 
m1 = torch.FloatTensor([[3,3]])
m2 = torch.FloatTensor([[2,2]])
print(m1+m2)


tensor([[5., 5.]])


In [21]:
# Vector +scalar
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([3]) # 3 -> [[3,3]]
print(m1+m2)

tensor([[4., 5.]])


In [22]:
# 2 x 1 Vector +1 x 2 Vector
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([[3],[4]]) # 3 -> [[3,3]] 4->[[4,4]]
print(m1+m2)

tensor([[4., 5.],
        [5., 6.]])


## Multiplication vs Matrix Multiplication

In [23]:
print()
print("-----------------------")
print('Mul vs Matmul')
m1 = torch.FloatTensor([[1,2],[3,4]])
m2 = torch.FloatTensor([[1],[2]])
print('Shape of Matrix 1:', m1.shape) # 2x2
print('Shape of Matrix 2:', m2.shape) # 2x1
print(m1.matmul(m2)) # 2 x 1 일반적인 행렬 곱

m1 = torch.FloatTensor([[1,2],[3,4]])
m2 = torch.FloatTensor([[1],[2]])

print('Shape of Matrix 1:', m1.shape) # 2x2
print('Shape of Matrix 2:', m2.shape) # 2x1

print(m1*m2)
print(m1.mul(m2))


-----------------------
Mul vs Matmul
Shape of Matrix 1: torch.Size([2, 2])
Shape of Matrix 2: torch.Size([2, 1])
tensor([[ 5.],
        [11.]])
Shape of Matrix 1: torch.Size([2, 2])
Shape of Matrix 2: torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


In [24]:
t= torch.FloatTensor([1,2])
print(t.mean())

tensor(1.5000)


In [25]:
# can't use mean() on integere
t= torch.LongTensor([1,2])
try : 
  print(t.mean())
except Exception as exc:
  print(exc)
  

Can only calculate the mean of floating types. Got Long instead.


In [26]:
t= torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [27]:
print(t.mean())
print(t.mean(dim=0))
print(t.mean(dim=1))
print(t.mean(dim=-1))

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


## Sum

In [29]:
print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=1))
print(t.sum(dim=-1))

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


## Max and Argmax

In [30]:
t= torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [31]:
print(t.max())

tensor(4.)


In [33]:
print(t.max(dim=0))
print('max: ',t.max(dim=0)[0])
print('Argmax: ',t.max(dim=0)[1])

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
max:  tensor([3., 4.])
Argmax:  tensor([1, 1])


In [34]:
print(t.max(dim=1))
print(t.max(dim=-1))


torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


In [39]:
t= np.array([[[0,1,2],
             [3,4,5]],
            [[6,7,8],
             [9,10,11]]])
ft=torch.FloatTensor(t)
print(ft.shape)

torch.Size([2, 2, 3])


## View(Reshape)

In [41]:
print (ft.view([-1,3]))
print (ft.view([-1,3]).shape)


tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


## Squeeze

In [43]:
ft = torch.FloatTensor([[0],[1],[2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [44]:
print(ft.squeeze())
print(ft.squeeze().shape)


tensor([0., 1., 2.])
torch.Size([3])


## Unsqueeze

In [53]:
ft = torch.FloatTensor([0,1,2])
print(ft.shape)

torch.Size([3])


In [54]:
print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [55]:
print (ft.view([1,-1]))
print (ft.view([1,-1]).shape)


tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [56]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [57]:
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


## Type Casting

In [58]:
lt = torch.LongTensor([1,2,3,4])
print(lt)

tensor([1, 2, 3, 4])


In [60]:
print(lt.float())

tensor([1., 2., 3., 4.])


In [61]:
bt = torch.ByteTensor([True,False,False,True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [62]:
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


## Concatenate


In [0]:
x= torch.FloatTensor([[1,2],[3,4]])
y= torch.FloatTensor([[5,6],[7,8]])

In [64]:
print(torch.cat([x,y],dim=0))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])


In [65]:
print(torch.cat([x,y],dim=1))


tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


## Stacking 

In [0]:
x= torch.FloatTensor([1,4])
y= torch.FloatTensor([2,5])
z= torch.FloatTensor([3,6])



In [69]:
print(torch.stack([x,y,z]))
print(torch.stack([x,y,z],dim =1))


tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [70]:
print(torch.cat([x.unsqueeze(0),y.unsqueeze(0),z.unsqueeze(0)],dim=0))


tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


## Ones and Zeros

In [73]:
x = torch.FloatTensor([[0,1,2],[2,1,0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [74]:
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


## In - place Operation

In [0]:
x= torch.FloatTensor([[1,2],[3,4]])

In [76]:
print(x.mul(2.))
print(x)
print(x.mul_(2.))
print(x)


tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])


## lab 2 Linear

In [0]:
x_train = torch.FloatTensor([[1],[2],[3]]) # 데이터 정의
y_train = torch.FloatTensor([[2],[4],[6]])

W= torch.zeros(1,requires_grad=True) # 가설 초기화
b= torch.zeros(1,requires_grad=True)

optimizer = torch.optim.SGD([W, b], lr=0.01)  # Optimizer 정의

nb_epochs = 100
for epoch in range(1,nb_epochs+1): # 반복
  hypothesis = x_train * W +b # 가설 예측
  cost = torch.mean((hypothesis-y_train)**2) # cost 계산

  optimizer.zero_grad() #optimizer로 학습
  cost.backward()
  optimizer.step()


In [0]:
from google.colab import drive
drive.mount('/content/drive')